# Generated by Django 3.2.2 on 2021-05-13 19:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('brand_name', models.CharField(max_length=50, unique=True, verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'brand',
                'ordering': ('brand_name',),
            },
        ),
        migrations.CreateModel(
            name='ClothTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('cloth_type', models.CharField(max_length=20, unique=True, verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Cloth type',
                'verbose_name_plural': 'Cloth types',
                'db_table': 'cloth_type',
                'ordering': ('cloth_type',),
            },
        ),
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('color_name', models.CharField(max_length=20, unique=True, verbose_name='Color Name')),
                ('color_hex', models.CharField(max_length=20, unique=True, verbose_name='Color Hex')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'db_table': 'color',
                'ordering': ('color_name',),
            },
        ),
        migrations.CreateModel(
            name='MaterialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('material', models.CharField(max_length=20, unique=True, verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'db_table': 'material',
                'ordering': ('material',),
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('basic_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Basic Prise')),
                ('gender', models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman'), ('Kids', 'Kids')], max_length=5, verbose_name='Gender')),
                ('description', models.TextField(verbose_name='Description')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('brand_name', models.ManyToManyField(to='product.BrandModel', verbose_name='Brand')),
                ('cloth_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cloth_type', to='product.clothtypemodel', verbose_name='ClothType')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_material', to='product.materialmodel', verbose_name='Material')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductPropertyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3, verbose_name='Size')),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='product_images/%Y/%m/%d', verbose_name='Image')),
                ('color', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.colormodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
