# Generated by Django 3.2.2 on 2021-05-16 10:39

from django.db import migrations, models
import django.db.models.deletion
import fashion_store.apps.images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('image', models.ImageField(null=True, upload_to='images/%Y/%m/%d', validators=[fashion_store.apps.images.models.validate_file_size])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productpropertymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
